CSSK-1 Docker container with CS simulator and Kafka was prepared
bwsw/cs-simulator-kafka pull request #14
Opened 2017-11-08 05:23 UTC by MedvedevBW

2017-11-08 06:45 UTC, MedvedevBW commented
[run tests]

2017-11-08 06:53 UTC, MedvedevBW commented
[run tests]

2017-11-08 06:55 UTC, MedvedevBW commented
[run tests]

2017-11-08 08:44 UTC, MedvedevBW commented
[run tests]

2017-11-08 09:44 UTC, MedvedevBW commented
[run tests]

2017-11-08 09:55 UTC, MedvedevBW commented
[run tests]

2017-11-08 10:02 UTC, MedvedevBW commented
[run tests]

2017-11-08 10:15 UTC, MedvedevBW commented
[run tests]

2017-11-08 11:09 UTC, MedvedevBW commented
[run tests]

2017-11-08 11:16 UTC, MedvedevBW commented
[run tests]

2017-11-08 11:35 UTC, MedvedevBW commented
[run tests]

2017-11-08 11:45 UTC, MedvedevBW commented
[run tests]

2017-11-09 04:43 UTC, MedvedevBW commented
[run tests]

2017-11-09 04:57 UTC, MedvedevBW commented
[run tests]

2017-11-09 05:08 UTC, MedvedevBW commented
[run tests]

2017-11-09 08:13 UTC, MedvedevBW commented
[run tests]

2017-11-09 09:03 UTC, MedvedevBW commented
[run tests]

2017-11-10 04:03 UTC, netpoint-dc requested changes

2017-11-10 04:03 UTC, netpoint-dc commented on version
> +1.0
Change version to 4.9.3

2017-11-10 04:58 UTC, merged